### ISSUE TITLE
关于构建流程

### ISSUE THREAD

**Issue by Enter-tainer** [OI-wiki/Roadmap#1]
看样子两个 png 文件应该由graphviz编译出来的吧，有没有考虑用 CI 之类的东西自动化呢？

**Comment by sshwy** [comment]
目前的工作比较多吧，在本地调代码然后直接构建的，构建的时间大概5秒左右。而且这个图尚有缺陷，在本地调试的话效率更高，因此CI暂不需要。可能当后期要部署前端的时候可以考虑。

**Comment by Enter-tainer** [comment]
我在想的是..这种编译出来的东西(二进制文件)实际上是不适合放到repo里的, 理论上应该让CI构建, 然后传到它应该在的地方
